name: hg_shopping_cart
description: A new Flutter project.

version: 1.0.0+1

environment:
sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.0.0
  # Value equality
  equatable: ^1.0.1
  # Functional programming thingies
  dartz: ^0.8.9
  json_annotation: 3.0.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  lottie: 0.3.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  scoped_model: 1.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_launcher_name: "^0.0.1"
  test: any
  dev_test: any
  mockito: ^4.1.1
  json_serializable: 3.3.0
  build_runner: 1.10.0

flutter_launcher_name:
  name: "Cart"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/appLauncher.png"
  image_path_android: "assets/launcher/appLauncher.png"

#flutter_test:
#  sdk: flutter
#  mockito: ^4.1.1
##  hive_generator: ^0.7.0+2
#  build_runner: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/